### ISSUE TITLE
Using amp; instead of & in HTML

### ISSUE THREAD

**Issue by griffinlacek** [codenamesen/prj-rev-bwfs-dasmoto#1]
In HTML when using & it's best to use the HTML code & since the browser doesn't always know what & is inside of HTML. Check this out for more codes: http://www.html.am/html-codes/

https://github.com/codenamesen/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsandCrafts/index.html#L5
https://github.com/codenamesen/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsandCrafts/index.html#L12

**Comment by codenamesen** [comment]
Got it.
