### ISSUE TITLE
Using html in CSS

### ISSUE THREAD

**Issue by griffinlacek** [codenamesen/prj-rev-bwfs-dasmoto#3]
Nothing wrong with using html to set font-family for the page, but body is often used instead as it directly influences children elements. Here's a good discussion on this: https://css-tricks.com/html-vs-body-in-css/

https://github.com/codenamesen/prj-rev-bwfs-dasmoto/blob/master/DasmotosArtsandCrafts/resources/css/style.css#L1-L3

**Comment by codenamesen** [comment]
Thank you I will check out the resource mentioned.
